import type { ProviderFormData } from '../types/provider';

export const PRESET_PROVIDERS: ProviderFormData[] = [
  {
    name: 'DeepSeek',
    type: 'official',
    apiType: 'openai',
    apiBase: 'https://api.deepseek.com',
    apiKey: '',
    website: 'https://www.deepseek.com',
    cliUrls: {
      'claude-code': 'https://api.deepseek.com',
      codex: 'https://api.deepseek.com',
      'gemini-cli': 'https://api.deepseek.com',
      opencode: 'https://api.deepseek.com',
    },
    headers: {},
    models: ['deepseek-chat', 'deepseek-reasoner'],
  },
  {
    name: '智谱 GLM',
    type: 'official',
    apiType: 'openai',
    apiBase: 'https://open.bigmodel.cn/api/paas/v4',
    apiKey: '',
    website: 'https://open.bigmodel.cn',
    cliUrls: {
      'claude-code': 'https://open.bigmodel.cn/api/paas/v4',
      codex: 'https://open.bigmodel.cn/api/paas/v4',
    },
    headers: {},
    models: ['glm-4-plus', 'glm-4-flash', 'glm-4-long'],
  },
  {
    name: 'Kimi (Moonshot)',
    type: 'official',
    apiType: 'openai',
    apiBase: 'https://api.moonshot.cn/v1',
    apiKey: '',
    website: 'https://kimi.moonshot.cn',
    cliUrls: {
      'claude-code': 'https://api.moonshot.cn/v1',
      codex: 'https://api.moonshot.cn/v1',
    },
    headers: {},
    models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
  },
  {
    name: 'MiniMax',
    type: 'official',
    apiType: 'openai',
    apiBase: 'https://api.minimax.chat/v1',
    apiKey: '',
    website: 'https://www.minimax.io',
    cliUrls: {},
    headers: {},
    models: ['abab6.5s-chat', 'abab7-chat'],
  },
  {
    name: '通义千问 (DashScope)',
    type: 'official',
    apiType: 'openai',
    apiBase: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    apiKey: '',
    website: 'https://tongyi.aliyun.com',
    cliUrls: {
      'claude-code': 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    },
    headers: {},
    models: ['qwen-max', 'qwen-plus', 'qwen-turbo', 'qwen-coder-plus'],
  },
  {
    name: '字节豆包',
    type: 'official',
    apiType: 'openai',
    apiBase: 'https://ark.cn-beijing.volces.com/api/v3',
    apiKey: '',
    website: 'https://www.volcengine.com/product/doubao',
    cliUrls: {},
    headers: {},
    models: ['doubao-pro-32k', 'doubao-pro-128k', 'doubao-lite-32k'],
  },
  {
    name: '百川 (Baichuan)',
    type: 'official',
    apiType: 'openai',
    apiBase: 'https://api.baichuan-ai.com/v1',
    apiKey: '',
    website: 'https://www.baichuan-ai.com',
    cliUrls: {},
    headers: {},
    models: ['Baichuan4', 'Baichuan3-Turbo'],
  },
  {
    name: '讯飞星火',
    type: 'official',
    apiType: 'openai',
    apiBase: 'https://spark-api-open.xf-yun.com/v1',
    apiKey: '',
    website: 'https://xinghuo.xfyun.cn',
    cliUrls: {},
    headers: {},
    models: ['spark-4.0-ultra', 'spark-max', 'spark-pro'],
  },
  {
    name: '腾讯混元',
    type: 'official',
    apiType: 'openai',
    apiBase: 'https://api.hunyuan.cloud.tencent.com/v1',
    apiKey: '',
    website: 'https://hunyuan.tencent.com',
    cliUrls: {},
    headers: {},
    models: ['hunyuan-turbo', 'hunyuan-pro', 'hunyuan-lite'],
  },
  {
    name: 'SiliconFlow',
    type: 'official',
    apiType: 'openai',
    apiBase: 'https://api.siliconflow.cn/v1',
    apiKey: '',
    website: 'https://siliconflow.cn',
    cliUrls: {
      'claude-code': 'https://api.siliconflow.cn/v1',
      codex: 'https://api.siliconflow.cn/v1',
    },
    headers: {},
    models: ['deepseek-ai/DeepSeek-V3', 'Qwen/Qwen2.5-72B-Instruct', 'meta-llama/Meta-Llama-3.1-405B-Instruct'],
  },
  {
    name: 'OpenRouter',
    type: 'third-party',
    apiType: 'openai',
    apiBase: 'https://openrouter.ai/api/v1',
    apiKey: '',
    website: 'https://openrouter.ai',
    cliUrls: {},
    headers: {},
    models: [],
  },
  {
    name: 'Anthropic Official',
    type: 'official',
    apiType: 'anthropic',
    apiBase: 'https://api.anthropic.com',
    apiKey: '',
    website: 'https://www.anthropic.com',
    cliUrls: {
      'claude-code': 'https://api.anthropic.com',
    },
    headers: {},
    models: ['claude-opus-4-7', 'claude-sonnet-4-6', 'claude-haiku-4-5'],
  },
  {
    name: 'OpenAI Official',
    type: 'official',
    apiType: 'openai',
    apiBase: 'https://api.openai.com/v1',
    apiKey: '',
    website: 'https://platform.openai.com',
    cliUrls: {
      codex: 'https://api.openai.com/v1',
    },
    headers: {},
    models: ['gpt-4o', 'gpt-4-turbo', 'o3-mini'],
  },
  {
    name: 'Google Gemini',
    type: 'official',
    apiType: 'google',
    apiBase: 'https://generativelanguage.googleapis.com',
    apiKey: '',
    website: 'https://ai.google.dev',
    cliUrls: {
      'gemini-cli': 'https://generativelanguage.googleapis.com',
    },
    headers: {},
    models: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-2.0-flash'],
  },
];
